#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2013-2014 Oliver Tappe
# Distributed under the terms of the MIT License.

# -- Compatibility Check ------------------------------------------------------

# TODO: use 'python2' in the shebang once we have that symlink on Haiku
import logging
from HaikuPorter.Options import parseOptions
from HaikuPorter.Main import Main
import sys
if sys.version_info.major != 3:
    sys.exit('Sorry, haikuporter currently requires Python 3')

# -- Modules ------------------------------------------------------------------


# -- Start --------------------------------------------------------------------

logger = logging.getLogger("buildLogger")
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())

Main(*parseOptions())
